baseURL = "https://winsonwu.com/"
languageCode = "en"
title = "Winson Wu"
theme = "blowfish"

# 启用分页（比如博客文章列表）
[pagination]
  pagerSize = 10


# 菜单配置
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 2

  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 3

  [[menu.main]]
    name = "AI Weekly"
    url = "/weekly/"
    weight = 4

# 启用一些 Blowfish 推荐的功能
[params]
  # 网站描述
  description = "Personal site of Winson Wu: Resume, Products, and AI Weekly."

  # 显示文章日期
  showDate = true

  # 页脚版权信息
  footer = "© 2025 Winson Wu. Powered by Hugo + Blowfish"

  # 开启亮/暗模式切换
  colorScheme = "auto"

  # 社交链接（可选）
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/winson5566"

  [[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://linkedin.com/in/winsonwu"

